### ISSUE TITLE
不会是浙大吧？

### ISSUE THREAD

**Issue by tmplog** [AaronFang123/uniapp-demo#1]

**Comment by nado-dev** [comment]
不是哦，之前做着玩的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月14日(周一) 晚上9:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [AaronFang123/uniapp-demo] 不会是浙大吧？ (Issue #1)
